framework:
  mailer:
    dsn: "%env(MAILER_DSN)%"
    envelope:
      sender: "noreply@pintirest.com"
      recipients: ["foo@example.com", "bar@example.com"]
    headers:
      From: "Pintirest <noreply@pintirest.com>"
      Bcc: "baz@example.com"
      X-Custom-Header: "foobar"
